[project]
name = "dbt-acma-rrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.9.6",
    "dbt-duckdb>=1.9.3",
]
